-- 대장급여-상여등록-사원조회쿼리문
SELECT user_id,
       user_name,
       dept,
       hire_date,
       job_title
FROM   tb_user_master;
-- =========
-- 20251126
-- =========

-- 사원조회
SELECT *
FROM   tb_user_master;

-- =========
-- 20251127
-- =========

-- ===============================
-- TB_PAYROLL 샘플 데이터 (총 10건)
-- ===============================
-- 조건: PAYROLL_PERIOD='202509', PAYROLL_TYPE='급여', PAYROLL_NAME='2025년 9월 정기 급여대장', PAYROLL_DATE='2025-10-10' (모두 동일)

-- 1. 김사원 (H2025001)
INSERT INTO TB_PAYROLL (PAYROLL_CODE, COMPANY_CODE, USER_ID, PAYROLL_PERIOD, PAYROLL_NAME, PAYROLL_START_DATE, PAYROLL_END_DATE, PAYROLL_DATE, PAYROLL_TYPE, CREATED_BY, CREATE_DATE, UPDATED_BY, UPDATE_DATE)
VALUES ('P202509_01', 'ROOT', 'H2025001', '202509', '2025년 9월 정기 급여대장', DATE '2025-09-01', DATE '2025-09-30', DATE '2025-10-10', '급여', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE);

-- 2. 이대리 (S2024005)
INSERT INTO TB_PAYROLL (PAYROLL_CODE, COMPANY_CODE, USER_ID, PAYROLL_PERIOD, PAYROLL_NAME, PAYROLL_START_DATE, PAYROLL_END_DATE, PAYROLL_DATE, PAYROLL_TYPE, CREATED_BY, CREATE_DATE, UPDATED_BY, UPDATE_DATE)
VALUES ('P202509_02', 'ROOT', 'S2024005', '202509', '2025년 9월 정기 급여대장', DATE '2025-09-01', DATE '2025-09-30', DATE '2025-10-10', '급여', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE);

-- 3. 박과장 (D2023010)
INSERT INTO TB_PAYROLL (PAYROLL_CODE, COMPANY_CODE, USER_ID, PAYROLL_PERIOD, PAYROLL_NAME, PAYROLL_START_DATE, PAYROLL_END_DATE, PAYROLL_DATE, PAYROLL_TYPE, CREATED_BY, CREATE_DATE, UPDATED_BY, UPDATE_DATE)
VALUES ('P202509_03', 'ROOT', 'D2023010', '202509', '2025년 9월 정기 급여대장', DATE '2025-09-01', DATE '2025-09-30', DATE '2025-10-10', '급여', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE);

-- 4. 최부장 (P2019003)
INSERT INTO TB_PAYROLL (PAYROLL_CODE, COMPANY_CODE, USER_ID, PAYROLL_PERIOD, PAYROLL_NAME, PAYROLL_START_DATE, PAYROLL_END_DATE, PAYROLL_DATE, PAYROLL_TYPE, CREATED_BY, CREATE_DATE, UPDATED_BY, UPDATE_DATE)
VALUES ('P202509_04', 'ROOT', 'P2019003', '202509', '2025년 9월 정기 급여대장', DATE '2025-09-01', DATE '2025-09-30', DATE '2025-10-10', '급여', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE);

-- 5. 정주임 (D2025002)
INSERT INTO TB_PAYROLL (PAYROLL_CODE, COMPANY_CODE, USER_ID, PAYROLL_PERIOD, PAYROLL_NAME, PAYROLL_START_DATE, PAYROLL_END_DATE, PAYROLL_DATE, PAYROLL_TYPE, CREATED_BY, CREATE_DATE, UPDATED_BY, UPDATE_DATE)
VALUES ('P202509_05', 'ROOT', 'D2025002', '202509', '2025년 9월 정기 급여대장', DATE '2025-09-01', DATE '2025-09-30', DATE '2025-10-10', '급여', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE);

-- 6. 윤사원 (S2025008)
INSERT INTO TB_PAYROLL (PAYROLL_CODE, COMPANY_CODE, USER_ID, PAYROLL_PERIOD, PAYROLL_NAME, PAYROLL_START_DATE, PAYROLL_END_DATE, PAYROLL_DATE, PAYROLL_TYPE, CREATED_BY, CREATE_DATE, UPDATED_BY, UPDATE_DATE)
VALUES ('P202509_06', 'ROOT', 'S2025008', '202509', '2025년 9월 정기 급여대장', DATE '2025-09-01', DATE '2025-09-30', DATE '2025-10-10', '급여', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE);

-- 7. 문과장 (H2022007)
INSERT INTO TB_PAYROLL (PAYROLL_CODE, COMPANY_CODE, USER_ID, PAYROLL_PERIOD, PAYROLL_NAME, PAYROLL_START_DATE, PAYROLL_END_DATE, PAYROLL_DATE, PAYROLL_TYPE, CREATED_BY, CREATE_DATE, UPDATED_BY, UPDATE_DATE)
VALUES ('P202509_07', 'ROOT', 'H2022007', '202509', '2025년 9월 정기 급여대장', DATE '2025-09-01', DATE '2025-09-30', DATE '2025-10-10', '급여', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE);

-- 8. 한대리 (F2023012)
INSERT INTO TB_PAYROLL (PAYROLL_CODE, COMPANY_CODE, USER_ID, PAYROLL_PERIOD, PAYROLL_NAME, PAYROLL_START_DATE, PAYROLL_END_DATE, PAYROLL_DATE, PAYROLL_TYPE, CREATED_BY, CREATE_DATE, UPDATED_BY, UPDATE_DATE)
VALUES ('P202509_08', 'ROOT', 'F2023012', '202509', '2025년 9월 정기 급여대장', DATE '2025-09-01', DATE '2025-09-30', DATE '2025-10-10', '급여', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE);

-- 9. 오주임 (D2024009)
INSERT INTO TB_PAYROLL (PAYROLL_CODE, COMPANY_CODE, USER_ID, PAYROLL_PERIOD, PAYROLL_NAME, PAYROLL_START_DATE, PAYROLL_END_DATE, PAYROLL_DATE, PAYROLL_TYPE, CREATED_BY, CREATE_DATE, UPDATED_BY, UPDATE_DATE)
VALUES ('P202509_09', 'ROOT', 'D2024009', '202509', '2025년 9월 정기 급여대장', DATE '2025-09-01', DATE '2025-09-30', DATE '2025-10-10', '급여', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE);

-- 10. 신사원 (M2025015)
INSERT INTO TB_PAYROLL (PAYROLL_CODE, COMPANY_CODE, USER_ID, PAYROLL_PERIOD, PAYROLL_NAME, PAYROLL_START_DATE, PAYROLL_END_DATE, PAYROLL_DATE, PAYROLL_TYPE, CREATED_BY, CREATE_DATE, UPDATED_BY, UPDATE_DATE)
VALUES ('P202509_10', 'ROOT', 'M2025015', '202509', '2025년 9월 정기 급여대장', DATE '2025-09-01', DATE '2025-09-30', DATE '2025-10-10', '급여', 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE);



-- ================================
-- TB_DEPT_MASTER 샘플 데이터 INSERT
-- ================================
-- CEO
INSERT INTO TB_DEPT_MASTER(DEPT_CODE, COMPANY_CODE, DEPT_NAME, UPPER_DEPT_NO, DEPT_LEVEL, START_DATE, STATUS, CREATED_BY, CREATE_DATE)
VALUES('D000','C001','CEO',NULL,1,SYSDATE,'0','ADMIN',SYSDATE);

-- 재무총괄 / 회계부
INSERT INTO TB_DEPT_MASTER(DEPT_CODE, COMPANY_CODE, DEPT_NAME, UPPER_DEPT_NO, DEPT_LEVEL, START_DATE, STATUS, CREATED_BY, CREATE_DATE)
VALUES('D100','C001','재무총괄', 'D000',2,SYSDATE,'0','ADMIN',SYSDATE);

INSERT INTO TB_DEPT_MASTER(DEPT_CODE, COMPANY_CODE, DEPT_NAME, UPPER_DEPT_NO, DEPT_LEVEL, START_DATE, STATUS, CREATED_BY, CREATE_DATE)
VALUES('D110','C001','회계부','D100',3,SYSDATE,'0','ADMIN',SYSDATE);

INSERT INTO TB_DEPT_MASTER(DEPT_CODE, COMPANY_CODE, DEPT_NAME, UPPER_DEPT_NO, DEPT_LEVEL, START_DATE, STATUS, CREATED_BY, CREATE_DATE)
VALUES('D111','C001','재무회계팀','D110',4,SYSDATE,'0','ADMIN',SYSDATE);

INSERT INTO TB_DEPT_MASTER(DEPT_CODE, COMPANY_CODE, DEPT_NAME, UPPER_DEPT_NO, DEPT_LEVEL, START_DATE, STATUS, CREATED_BY, CREATE_DATE)
VALUES('D112','C001','관리회계팀','D110',4,SYSDATE,'0','ADMIN',SYSDATE);

INSERT INTO TB_DEPT_MASTER(DEPT_CODE, COMPANY_CODE, DEPT_NAME, UPPER_DEPT_NO, DEPT_LEVEL, START_DATE, STATUS, CREATED_BY, CREATE_DATE)
VALUES('D113','C001','세무팀','D110',4,SYSDATE,'0','ADMIN',SYSDATE);

-- 운영총괄 / 물류부, 자재부
INSERT INTO TB_DEPT_MASTER(DEPT_CODE, COMPANY_CODE, DEPT_NAME, UPPER_DEPT_NO, DEPT_LEVEL, START_DATE, STATUS, CREATED_BY, CREATE_DATE)
VALUES('D200','C001','운영총괄','D000',2,SYSDATE,'0','ADMIN',SYSDATE);

INSERT INTO TB_DEPT_MASTER(DEPT_CODE, COMPANY_CODE, DEPT_NAME, UPPER_DEPT_NO, DEPT_LEVEL, START_DATE, STATUS, CREATED_BY, CREATE_DATE)
VALUES('D210','C001','물류부','D200',3,SYSDATE,'0','ADMIN',SYSDATE);

INSERT INTO TB_DEPT_MASTER(DEPT_CODE, COMPANY_CODE, DEPT_NAME, UPPER_DEPT_NO, DEPT_LEVEL, START_DATE, STATUS, CREATED_BY, CREATE_DATE)
VALUES('D211','C001','창고관리팀','D210',4,SYSDATE,'0','ADMIN',SYSDATE);

INSERT INTO TB_DEPT_MASTER(DEPT_CODE, COMPANY_CODE, DEPT_NAME, UPPER_DEPT_NO, DEPT_LEVEL, START_DATE, STATUS, CREATED_BY, CREATE_DATE)
VALUES('D212','C001','배송팀','D210',4,SYSDATE,'0','ADMIN',SYSDATE);

INSERT INTO TB_DEPT_MASTER(DEPT_CODE, COMPANY_CODE, DEPT_NAME, UPPER_DEPT_NO, DEPT_LEVEL, START_DATE, STATUS, CREATED_BY, CREATE_DATE)
VALUES('D213','C001','수송관리팀','D210',4,SYSDATE,'0','ADMIN',SYSDATE);

INSERT INTO TB_DEPT_MASTER(DEPT_CODE, COMPANY_CODE, DEPT_NAME, UPPER_DEPT_NO, DEPT_LEVEL, START_DATE, STATUS, CREATED_BY, CREATE_DATE)
VALUES('D220','C001','자재부','D200',3,SYSDATE,'0','ADMIN',SYSDATE);

INSERT INTO TB_DEPT_MASTER(DEPT_CODE, COMPANY_CODE, DEPT_NAME, UPPER_DEPT_NO, DEPT_LEVEL, START_DATE, STATUS, CREATED_BY, CREATE_DATE)
VALUES('D221','C001','구매팀','D220',4,SYSDATE,'0','ADMIN',SYSDATE);

INSERT INTO TB_DEPT_MASTER(DEPT_CODE, COMPANY_CODE, DEPT_NAME, UPPER_DEPT_NO, DEPT_LEVEL, START_DATE, STATUS, CREATED_BY, CREATE_DATE)
VALUES('D222','C001','재고관리팀','D220',4,SYSDATE,'0','ADMIN',SYSDATE);

INSERT INTO TB_DEPT_MASTER(DEPT_CODE, COMPANY_CODE, DEPT_NAME, UPPER_DEPT_NO, DEPT_LEVEL, START_DATE, STATUS, CREATED_BY, CREATE_DATE)
VALUES('D223','C001','자재기획팀','D220',4,SYSDATE,'0','ADMIN',SYSDATE);

-- 기술총괄 / 개발부
INSERT INTO TB_DEPT_MASTER(DEPT_CODE, COMPANY_CODE, DEPT_NAME, UPPER_DEPT_NO, DEPT_LEVEL, START_DATE, STATUS, CREATED_BY, CREATE_DATE)
VALUES('D300','C001','기술총괄','D000',2,SYSDATE,'0','ADMIN',SYSDATE);

INSERT INTO TB_DEPT_MASTER(DEPT_CODE, COMPANY_CODE, DEPT_NAME, UPPER_DEPT_NO, DEPT_LEVEL, START_DATE, STATUS, CREATED_BY, CREATE_DATE)
VALUES('D310','C001','개발부','D300',3,SYSDATE,'0','ADMIN',SYSDATE);

INSERT INTO TB_DEPT_MASTER(DEPT_CODE, COMPANY_CODE, DEPT_NAME, UPPER_DEPT_NO, DEPT_LEVEL, START_DATE, STATUS, CREATED_BY, CREATE_DATE)
VALUES('D311','C001','시스템운영팀','D310',4,SYSDATE,'0','ADMIN',SYSDATE);

INSERT INTO TB_DEPT_MASTER(DEPT_CODE, COMPANY_CODE, DEPT_NAME, UPPER_DEPT_NO, DEPT_LEVEL, START_DATE, STATUS, CREATED_BY, CREATE_DATE)
VALUES('D312','C001','ERP개발팀','D310',4,SYSDATE,'0','ADMIN',SYSDATE);

INSERT INTO TB_DEPT_MASTER(DEPT_CODE, COMPANY_CODE, DEPT_NAME, UPPER_DEPT_NO, DEPT_LEVEL, START_DATE, STATUS, CREATED_BY, CREATE_DATE)
VALUES('D313','C001','인프라팀','D310',4,SYSDATE,'0','ADMIN',SYSDATE);

-- 인사총괄 / 인사부
INSERT INTO TB_DEPT_MASTER(DEPT_CODE, COMPANY_CODE, DEPT_NAME, UPPER_DEPT_NO, DEPT_LEVEL, START_DATE, STATUS, CREATED_BY, CREATE_DATE)
VALUES('D400','C001','인사총괄','D000',2,SYSDATE,'0','ADMIN',SYSDATE);

INSERT INTO TB_DEPT_MASTER(DEPT_CODE, COMPANY_CODE, DEPT_NAME, UPPER_DEPT_NO, DEPT_LEVEL, START_DATE, STATUS, CREATED_BY, CREATE_DATE)
VALUES('D410','C001','인사부','D400',3,SYSDATE,'0','ADMIN',SYSDATE);

INSERT INTO TB_DEPT_MASTER(DEPT_CODE, COMPANY_CODE, DEPT_NAME, UPPER_DEPT_NO, DEPT_LEVEL, START_DATE, STATUS, CREATED_BY, CREATE_DATE)
VALUES('D411','C001','인재채용팀','D410',4,SYSDATE,'0','ADMIN',SYSDATE);

INSERT INTO TB_DEPT_MASTER(DEPT_CODE, COMPANY_CODE, DEPT_NAME, UPPER_DEPT_NO, DEPT_LEVEL, START_DATE, STATUS, CREATED_BY, CREATE_DATE)
VALUES('D412','C001','급여/복리후생팀','D410',4,SYSDATE,'0','ADMIN',SYSDATE);

INSERT INTO TB_DEPT_MASTER(DEPT_CODE, COMPANY_CODE, DEPT_NAME, UPPER_DEPT_NO, DEPT_LEVEL, START_DATE, STATUS, CREATED_BY, CREATE_DATE)
VALUES('D413','C001','교육/평가팀','D410',4,SYSDATE,'0','ADMIN',SYSDATE);

-- 마케팅총괄 / 마케팅부
INSERT INTO TB_DEPT_MASTER(DEPT_CODE, COMPANY_CODE, DEPT_NAME, UPPER_DEPT_NO, DEPT_LEVEL, START_DATE, STATUS, CREATED_BY, CREATE_DATE)
VALUES('D500','C001','마케팅총괄','D000',2,SYSDATE,'0','ADMIN',SYSDATE);

INSERT INTO TB_DEPT_MASTER(DEPT_CODE, COMPANY_CODE, DEPT_NAME, UPPER_DEPT_NO, DEPT_LEVEL, START_DATE, STATUS, CREATED_BY, CREATE_DATE)
VALUES('D510','C001','마케팅부','D500',3,SYSDATE,'0','ADMIN',SYSDATE);

INSERT INTO TB_DEPT_MASTER(DEPT_CODE, COMPANY_CODE, DEPT_NAME, UPPER_DEPT_NO, DEPT_LEVEL, START_DATE, STATUS, CREATED_BY, CREATE_DATE)
VALUES('D511','C001','브랜드마케팅팀','D510',4,SYSDATE,'0','ADMIN',SYSDATE);

INSERT INTO TB_DEPT_MASTER(DEPT_CODE, COMPANY_CODE, DEPT_NAME, UPPER_DEPT_NO, DEPT_LEVEL, START_DATE, STATUS, CREATED_BY, CREATE_DATE)
VALUES('D512','C001','디지털마케팅팀','D510',4,SYSDATE,'0','ADMIN',SYSDATE);

INSERT INTO TB_DEPT_MASTER(DEPT_CODE, COMPANY_CODE, DEPT_NAME, UPPER_DEPT_NO, DEPT_LEVEL, START_DATE, STATUS, CREATED_BY, CREATE_DATE)
VALUES('D513','C001','CRM/고객분석팀','D510',4,SYSDATE,'0','ADMIN',SYSDATE);

-- 품질부
INSERT INTO TB_DEPT_MASTER(DEPT_CODE, COMPANY_CODE, DEPT_NAME, UPPER_DEPT_NO, DEPT_LEVEL, START_DATE, STATUS, CREATED_BY, CREATE_DATE)
VALUES('D600','C001','품질부','D000',2,SYSDATE,'0','ADMIN',SYSDATE);

INSERT INTO TB_DEPT_MASTER(DEPT_CODE, COMPANY_CODE, DEPT_NAME, UPPER_DEPT_NO, DEPT_LEVEL, START_DATE, STATUS, CREATED_BY, CREATE_DATE)
VALUES('D611','C001','품질검사팀','D600',4,SYSDATE,'0','ADMIN',SYSDATE);

INSERT INTO TB_DEPT_MASTER(DEPT_CODE, COMPANY_CODE, DEPT_NAME, UPPER_DEPT_NO, DEPT_LEVEL, START_DATE, STATUS, CREATED_BY, CREATE_DATE)
VALUES('D612','C001','불량관리팀','D600',4,SYSDATE,'0','ADMIN',SYSDATE);

INSERT INTO TB_DEPT_MASTER(DEPT_CODE, COMPANY_CODE, DEPT_NAME, UPPER_DEPT_NO, DEPT_LEVEL, START_DATE, STATUS, CREATED_BY, CREATE_DATE)
VALUES('D613','C001','품질개선팀','D600',4,SYSDATE,'0','ADMIN',SYSDATE);

-- 공통코드 부서 데이터 삭제
SELECT *
FROM   tb_cm_code;
SELECT *
FROM   tb_cm_code_group;
DELETE FROM tb_cm_code
WHERE group_code = '0B';
DELETE FROM tb_cm_code_group
WHERE group_code = '0B';