-- 대장급여-상여등록-사원조회쿼리문
SELECT user_id,
       user_name,
       dept,
       hire_date,
       job_title
FROM   tb_user_master;

-- 20251126
-- 사원조회
SELECT *
FROM   tb_user_master;

-- TB_USER_MASTER 샘플 데이터 (총 10건)
-- 1. 인사팀 김사원 (HR, 사원)
INSERT INTO TB_USER_MASTER (
    COMPANY_CODE, USER_ID, USER_NAME, BIRTH, TEL, EMAIL, HIRE_DATE, HIRE_TYPE, LEAVE_DATE, LEAVE_REASON, 
    ZIP_CODE, ADDRESS, DEPT, JOB_TITLE, POSITION, FAMILY_COUNT, CHILDREN_COUNT, HOUSEHOLDER, 
    BANK_NAME, ACCOUNT_NO, ACCOUNT_HOLDER, SALARY, USER_STATUS, USER_PHOTO, USER_FILE, REMARK, 
    CREATED_BY, CREATE_DATE, UPDATED_BY, UPDATE_DATE
) VALUES (
    'ROOT', 'H2025001', '김사원', DATE '1995-03-15', '010-1111-2222', 'kim.hr@root.com', DATE '2025-01-02', '정규직', NULL, NULL, 
    '03724', '서울 서대문구 증가로 24', '인사팀', '사원', '사원', 1, 0, 'Y', 
    '국민은행', '1234567890', '김사원', 35000000, '1', NULL, NULL, '신규 입사자', 
    'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE
);

-- 2. 영업팀 이대리 (SALES, 대리)
INSERT INTO TB_USER_MASTER (
    COMPANY_CODE, USER_ID, USER_NAME, BIRTH, TEL, EMAIL, HIRE_DATE, HIRE_TYPE, LEAVE_DATE, LEAVE_REASON, 
    ZIP_CODE, ADDRESS, DEPT, JOB_TITLE, POSITION, FAMILY_COUNT, CHILDREN_COUNT, HOUSEHOLDER, 
    BANK_NAME, ACCOUNT_NO, ACCOUNT_HOLDER, SALARY, USER_STATUS, USER_PHOTO, USER_FILE, REMARK, 
    CREATED_BY, CREATE_DATE, UPDATED_BY, UPDATE_DATE
) VALUES (
    'ROOT', 'S2024005', '이대리', DATE '1990-11-20', '010-3333-4444', 'lee.sales@root.com', DATE '2024-05-15', '정규직', NULL, NULL, 
    '06233', '서울 강남구 테헤란로 123', '영업팀', '대리', '대리', 2, 0, 'Y', 
    '신한은행', '1109876543', '이대리', 48000000, '1', NULL, NULL, '핵심 영업 인력', 
    'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE
);

-- 3. 개발팀 박과장 (DEV, 과장)
INSERT INTO TB_USER_MASTER (
    COMPANY_CODE, USER_ID, USER_NAME, BIRTH, TEL, EMAIL, HIRE_DATE, HIRE_TYPE, LEAVE_DATE, LEAVE_REASON, 
    ZIP_CODE, ADDRESS, DEPT, JOB_TITLE, POSITION, FAMILY_COUNT, CHILDREN_COUNT, HOUSEHOLDER, 
    BANK_NAME, ACCOUNT_NO, ACCOUNT_HOLDER, SALARY, USER_STATUS, USER_PHOTO, USER_FILE, REMARK, 
    CREATED_BY, CREATE_DATE, UPDATED_BY, UPDATE_DATE
) VALUES (
    'ROOT', 'D2023010', '박과장', DATE '1988-07-01', '010-5555-6666', 'park.dev@root.com', DATE '2023-03-01', '정규직', NULL, NULL, 
    '08826', '서울 관악구 남부순환로 150', '개발팀', '과장', '과장', 4, 2, 'Y', 
    '우리은행', '1000123456', '박과장', 65000000, '1', NULL, NULL, '팀 내 최고 개발자', 
    'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE
);

-- 4. 기획팀 최부장 (PLAN, 부장)
INSERT INTO TB_USER_MASTER (
    COMPANY_CODE, USER_ID, USER_NAME, BIRTH, TEL, EMAIL, HIRE_DATE, HIRE_TYPE, LEAVE_DATE, LEAVE_REASON, 
    ZIP_CODE, ADDRESS, DEPT, JOB_TITLE, POSITION, FAMILY_COUNT, CHILDREN_COUNT, HOUSEHOLDER, 
    BANK_NAME, ACCOUNT_NO, ACCOUNT_HOLDER, SALARY, USER_STATUS, USER_PHOTO, USER_FILE, REMARK, 
    CREATED_BY, CREATE_DATE, UPDATED_BY, UPDATE_DATE
) VALUES (
    'ROOT', 'P2019003', '최부장', DATE '1980-01-10', '010-7777-8888', 'choi.plan@root.com', DATE '2019-10-01', '정규직', NULL, NULL, 
    '21990', '인천 연수구 송도과학로 10', '기획팀', '부장', '부장', 3, 1, 'Y', 
    '농협은행', '3024567890', '최부장', 80000000, '1', NULL, NULL, '사업 기획 총괄', 
    'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE
);

-- 5. 개발팀 정주임 (DEV, 주임)
INSERT INTO TB_USER_MASTER (
    COMPANY_CODE, USER_ID, USER_NAME, BIRTH, TEL, EMAIL, HIRE_DATE, HIRE_TYPE, LEAVE_DATE, LEAVE_REASON, 
    ZIP_CODE, ADDRESS, DEPT, JOB_TITLE, POSITION, FAMILY_COUNT, CHILDREN_COUNT, HOUSEHOLDER, 
    BANK_NAME, ACCOUNT_NO, ACCOUNT_HOLDER, SALARY, USER_STATUS, USER_PHOTO, USER_FILE, REMARK, 
    CREATED_BY, CREATE_DATE, UPDATED_BY, UPDATE_DATE
) VALUES (
    'ROOT', 'D2025002', '정주임', DATE '1998-04-22', '010-9999-0000', 'jung.dev@root.com', DATE '2025-04-10', '계약직', NULL, NULL, 
    '41131', '경기 고양시 일산동구 중앙로 50', '개발팀', '주임', '주임', 1, 0, 'Y', 
    '신한은행', '1101234567', '정주임', 38000000, '1', NULL, NULL, '6개월 계약직 (재직)', 
    'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE
);

-- 6. 영업팀 윤사원 (SALES, 사원)
INSERT INTO TB_USER_MASTER (
    COMPANY_CODE, USER_ID, USER_NAME, BIRTH, TEL, EMAIL, HIRE_DATE, HIRE_TYPE, LEAVE_DATE, LEAVE_REASON, 
    ZIP_CODE, ADDRESS, DEPT, JOB_TITLE, POSITION, FAMILY_COUNT, CHILDREN_COUNT, HOUSEHOLDER, 
    BANK_NAME, ACCOUNT_NO, ACCOUNT_HOLDER, SALARY, USER_STATUS, USER_PHOTO, USER_FILE, REMARK, 
    CREATED_BY, CREATE_DATE, UPDATED_BY, UPDATE_DATE
) VALUES (
    'ROOT', 'S2025008', '윤사원', DATE '2000-08-05', '010-1234-5678', 'yoon.sales@root.com', DATE '2025-07-01', '정규직', NULL, NULL, 
    '34054', '대전 유성구 대덕대로 100', '영업팀', '사원', '사원', 1, 0, 'Y', 
    '국민은행', '3333098765', '윤사원', 34000000, '1', NULL, NULL, '신입 사원', 
    'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE
);

-- 7. 인사팀 문과장 (HR, 과장)
INSERT INTO TB_USER_MASTER (
    COMPANY_CODE, USER_ID, USER_NAME, BIRTH, TEL, EMAIL, HIRE_DATE, HIRE_TYPE, LEAVE_DATE, LEAVE_REASON, 
    ZIP_CODE, ADDRESS, DEPT, JOB_TITLE, POSITION, FAMILY_COUNT, CHILDREN_COUNT, HOUSEHOLDER, 
    BANK_NAME, ACCOUNT_NO, ACCOUNT_HOLDER, SALARY, USER_STATUS, USER_PHOTO, USER_FILE, REMARK, 
    CREATED_BY, CREATE_DATE, UPDATED_BY, UPDATE_DATE
) VALUES (
    'ROOT', 'H2022007', '문과장', DATE '1985-02-28', '010-2468-1357', 'moon.hr@root.com', DATE '2022-09-01', '정규직', NULL, NULL, 
    '47246', '부산 부산진구 중앙대로 800', '인사팀', '과장', '과장', 3, 1, 'Y', 
    '하나은행', '4567890123', '문과장', 59000000, '1', NULL, NULL, '급여 담당자', 
    'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE
);

-- 8. 재무팀 한대리 (FINANCE, 대리)
INSERT INTO TB_USER_MASTER (
    COMPANY_CODE, USER_ID, USER_NAME, BIRTH, TEL, EMAIL, HIRE_DATE, HIRE_TYPE, LEAVE_DATE, LEAVE_REASON, 
    ZIP_CODE, ADDRESS, DEPT, JOB_TITLE, POSITION, FAMILY_COUNT, CHILDREN_COUNT, HOUSEHOLDER, 
    BANK_NAME, ACCOUNT_NO, ACCOUNT_HOLDER, SALARY, USER_STATUS, USER_PHOTO, USER_FILE, REMARK, 
    CREATED_BY, CREATE_DATE, UPDATED_BY, UPDATE_DATE
) VALUES (
    'ROOT', 'F2023012', '한대리', DATE '1992-12-03', '010-9876-5432', 'han.finance@root.com', DATE '2023-11-20', '정규직', NULL, NULL, 
    '04520', '서울 중구 을지로 50', '재무팀', '대리', '대리', 2, 0, 'Y', 
    '우리은행', '1000654321', '한대리', 45000000, '1', NULL, NULL, '회계 및 정산 담당', 
    'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE
);

-- 9. 개발팀 오주임 (DEV, 주임) - *퇴사 처리 예시*
INSERT INTO TB_USER_MASTER (
    COMPANY_CODE, USER_ID, USER_NAME, BIRTH, TEL, EMAIL, HIRE_DATE, HIRE_TYPE, LEAVE_DATE, LEAVE_REASON, 
    ZIP_CODE, ADDRESS, DEPT, JOB_TITLE, POSITION, FAMILY_COUNT, CHILDREN_COUNT, HOUSEHOLDER, 
    BANK_NAME, ACCOUNT_NO, ACCOUNT_HOLDER, SALARY, USER_STATUS, USER_PHOTO, USER_FILE, REMARK, 
    CREATED_BY, CREATE_DATE, UPDATED_BY, UPDATE_DATE
) VALUES (
    'ROOT', 'D2024009', '오주임', DATE '1997-06-18', '010-4321-8765', 'oh.dev@root.com', DATE '2024-01-01', '정규직', DATE '2025-01-31', '개인사정', 
    '13594', '경기 성남시 분당구 판교역로 200', '개발팀', '주임', '주임', 1, 0, '0', 
    '국민은행', '7777112233', '오주임', 40000000, '0', NULL, NULL, '2025년 1월 31일 퇴사', 
    'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE
);

-- 10. 마케팅팀 신사원 (MARKET, 사원)
INSERT INTO TB_USER_MASTER (
    COMPANY_CODE, USER_ID, USER_NAME, BIRTH, TEL, EMAIL, HIRE_DATE, HIRE_TYPE, LEAVE_DATE, LEAVE_REASON, 
    ZIP_CODE, ADDRESS, DEPT, JOB_TITLE, POSITION, FAMILY_COUNT, CHILDREN_COUNT, HOUSEHOLDER, 
    BANK_NAME, ACCOUNT_NO, ACCOUNT_HOLDER, SALARY, USER_STATUS, USER_PHOTO, USER_FILE, REMARK, 
    CREATED_BY, CREATE_DATE, UPDATED_BY, UPDATE_DATE
) VALUES (
    'ROOT', 'M2025015', '신사원', DATE '2001-10-25', '010-8642-7531', 'shin.market@root.com', DATE '2025-06-01', '정규직', NULL, NULL, 
    '07333', '서울 영등포구 국제금융로 10', '마케팅팀', '사원', '사원', 1, 0, 'Y', 
    '카카오뱅크', '3333224466', '신사원', 32000000, '1', NULL, NULL, '신규 채용', 
    'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE
);